/******************************************************************************/
#ifndef __LEDTABLE_H_
#define __LEDTABLE_H_
/******************************************************************************/

#ifdef _LEDTABLE_C_
#define GLOBAL
#else
#define GLOBAL extern
#endif
#include "bios.h"
/*
example:
GLOBAL char variable
GLOBAL bit flag
*/

//#define USE_LED_STATUS_INDEX

#define MASK_LED_1		1
#define MASK_LED_2		(1<<1)
#define MASK_LED_3		(1<<2)
#define MASK_LED_4		(1<<3)
#define MASK_LED_5		(1<<4)
#define MASK_LED_6		(1<<5)
#define MASK_LED_7		(1<<6)
#define MASK_LED_8		(1<<7)
#define MASK_LED_9		(1<<8)
#define MASK_LED_10		(1<<9)
#define MASK_LED_11		(1<<10)
#define MASK_LED_12		(1<<11)
#define MASK_LED_ALL	(0X0FFF)
#define MASK_LED_NONE	(0x0000)

#define STATUS_LED_0	(MASK_LED_NONE)
#define STATUS_LED_1	(MASK_LED_1)
#define STATUS_LED_2	(MASK_LED_2)
#define STATUS_LED_3	(MASK_LED_3)
#define STATUS_LED_4	(MASK_LED_4)
#define STATUS_LED_5	(MASK_LED_5)
#define STATUS_LED_6	(MASK_LED_6)
#define STATUS_LED_7	(MASK_LED_7)
#define STATUS_LED_8	(MASK_LED_8)
#define STATUS_LED_9	(MASK_LED_9)
#define STATUS_LED_10	(MASK_LED_10)
#define STATUS_LED_11	(MASK_LED_11)
#define STATUS_LED_12	(MASK_LED_12)
#define STATUS_LED_13	(MASK_LED_1|MASK_LED_2)
#define STATUS_LED_14	(MASK_LED_3|MASK_LED_4)
#define STATUS_LED_15	(MASK_LED_5|MASK_LED_6)
#define STATUS_LED_16	(MASK_LED_7|MASK_LED_8)
#define STATUS_LED_17	(MASK_LED_9|MASK_LED_10)
#define STATUS_LED_18	(MASK_LED_11|MASK_LED_12)
#define STATUS_LED_19	(MASK_LED_1|MASK_LED_3)
#define STATUS_LED_20	(MASK_LED_2|MASK_LED_4)
#define STATUS_LED_21	(MASK_LED_3|MASK_LED_5)
#define STATUS_LED_22	(MASK_LED_4|MASK_LED_6)
#define STATUS_LED_23	(MASK_LED_5|MASK_LED_7)
#define STATUS_LED_24	(MASK_LED_6|MASK_LED_8)
#define STATUS_LED_25	(MASK_LED_7|MASK_LED_9)
#define STATUS_LED_26	(MASK_LED_8|MASK_LED_10)
#define STATUS_LED_27	(MASK_LED_9|MASK_LED_11)
#define STATUS_LED_28	(MASK_LED_10|MASK_LED_12)
#define STATUS_LED_29	(MASK_LED_1|MASK_LED_12)
#define STATUS_LED_30	(MASK_LED_2|MASK_LED_11)
#define STATUS_LED_31	(MASK_LED_3|MASK_LED_10)
#define STATUS_LED_32	(MASK_LED_4|MASK_LED_9)
#define STATUS_LED_33	(MASK_LED_5|MASK_LED_8)
#define STATUS_LED_34	(MASK_LED_6|MASK_LED_7)
#define STATUS_LED_35	(MASK_LED_1|MASK_LED_5|MASK_LED_9)
#define STATUS_LED_36	(MASK_LED_2|MASK_LED_6|MASK_LED_10)
#define STATUS_LED_37	(MASK_LED_3|MASK_LED_7|MASK_LED_11)
#define STATUS_LED_38	(MASK_LED_4|MASK_LED_8|MASK_LED_12)
#define STATUS_LED_39	(MASK_LED_1|MASK_LED_2|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_40	(MASK_LED_3|MASK_LED_4|MASK_LED_9|MASK_LED_10)
#define STATUS_LED_41	(MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8)
#define STATUS_LED_42	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_43	(MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5)
#define STATUS_LED_44	(MASK_LED_6|MASK_LED_3|MASK_LED_4|MASK_LED_5)
#define STATUS_LED_45	(MASK_LED_6|MASK_LED_7|MASK_LED_4|MASK_LED_5)
#define STATUS_LED_46	(MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_5)
#define STATUS_LED_47	(MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9)
#define STATUS_LED_48	(MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10)
#define STATUS_LED_49	(MASK_LED_11|MASK_LED_8|MASK_LED_9|MASK_LED_10)
#define STATUS_LED_50	(MASK_LED_11|MASK_LED_12|MASK_LED_9|MASK_LED_10)
#define STATUS_LED_51	(MASK_LED_11|MASK_LED_12|MASK_LED_10)
#define STATUS_LED_52	(MASK_LED_11|MASK_LED_12)
#define STATUS_LED_53	(MASK_LED_12)
#define STATUS_LED_54	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4)
#define STATUS_LED_55	(MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8)
#define STATUS_LED_56	(MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_57	(MASK_LED_1|MASK_LED_3|MASK_LED_5|MASK_LED_7|MASK_LED_9|MASK_LED_11)
#define STATUS_LED_58	(MASK_LED_2|MASK_LED_4|MASK_LED_6|MASK_LED_8|MASK_LED_10|MASK_LED_12)
#define STATUS_LED_59	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6)
#define STATUS_LED_60	(MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_61	(MASK_LED_ALL)
#define STATUS_LED_62	(MASK_LED_NONE)

#define STATUS_LED_63	(MASK_LED_NONE)
#define STATUS_LED_64	(MASK_LED_NONE)
#define STATUS_LED_65	(MASK_LED_NONE)
#define STATUS_LED_66	(MASK_LED_NONE)
#define STATUS_LED_67	(MASK_LED_NONE)
#define STATUS_LED_68	(MASK_LED_NONE)
#define STATUS_LED_69	(MASK_LED_NONE)
#define STATUS_LED_70	(MASK_LED_NONE)
#define STATUS_LED_71	(MASK_LED_NONE)
#define STATUS_LED_72	(MASK_LED_NONE)
#define STATUS_LED_73	(MASK_LED_NONE)
#define STATUS_LED_74	(MASK_LED_NONE)
#define STATUS_LED_75	(MASK_LED_NONE)
#define STATUS_LED_76	(MASK_LED_NONE)
#define STATUS_LED_77	(MASK_LED_NONE)
#define STATUS_LED_78	(MASK_LED_NONE)
#define STATUS_LED_79	(MASK_LED_NONE)

#define STATUS_LED_80	(MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_81	(MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_82	(MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_83	(MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_84	(MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_85	(MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_86	(MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_87	(MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_88	(MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_89	(MASK_LED_11|MASK_LED_12)
#define STATUS_LED_90	(MASK_LED_12)
#define STATUS_LED_91	(MASK_LED_1|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_92	(MASK_LED_1|MASK_LED_2|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_93	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_94	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_95	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_96	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_97	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_98	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_99	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_100	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_12)
#define STATUS_LED_101	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11)
#define STATUS_LED_102	(MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11)
#define STATUS_LED_103	(MASK_LED_1|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_12)
#define STATUS_LED_104	(MASK_LED_1|MASK_LED_2|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_105	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_106	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_6|MASK_LED_7|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_107	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11|MASK_LED_12)
#define STATUS_LED_108	(MASK_LED_1)
#define STATUS_LED_109	(MASK_LED_1|MASK_LED_2)
#define STATUS_LED_110	(MASK_LED_1|MASK_LED_2|MASK_LED_3)
#define STATUS_LED_111	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4)
#define STATUS_LED_112	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5)
#define STATUS_LED_113	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6)
#define STATUS_LED_114	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7)
#define STATUS_LED_115	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8)
#define STATUS_LED_116	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9)
#define STATUS_LED_117	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10)
#define STATUS_LED_118	(MASK_LED_1|MASK_LED_2|MASK_LED_3|MASK_LED_4|MASK_LED_5|MASK_LED_6|MASK_LED_7|MASK_LED_8|MASK_LED_9|MASK_LED_10|MASK_LED_11)
#define STATUS_LED_119	(MASK_LED_NONE)
#define STATUS_LED_120	(MASK_LED_NONE)
#define STATUS_LED_121	(MASK_LED_NONE)
#define STATUS_LED_122	(MASK_LED_NONE)
#define STATUS_LED_123	(MASK_LED_NONE)
#define STATUS_LED_124	(MASK_LED_NONE)
#define STATUS_LED_125	(MASK_LED_NONE)
#define STATUS_LED_126	(MASK_LED_NONE)

#define STATUS_LED_END	(0xFFFF)

enum
{
	TIME_CODE_TA = 0,
	TIME_CODE_TB,
	TIME_CODE_TC,
	TIME_CODE_T1,
	TIME_CODE_T2,
	TIME_CODE_T3,
	TIME_CODE_T4,
	TIME_CODE_T5,
	TIME_CODE_T6,
	TIME_CODE_T10,
	TIME_CODE_T20,
	TIME_CODE_T30,
	TIME_CODE_T60,
	TIME_CODE_T90,
	TIME_CODE_T120,
	TIME_CODE_T180,
	TIME_CODE_T300,
	TIME_CODE_END = 0XFF,
};

#ifdef USE_LED_STATUS_INDEX
typedef struct
{
	Uint8 status_led;
	Uint8 time_code;
}MODULE_ELEMENT;
#else
typedef struct
{
	Uint16 status_led;
	Uint8 time_code;
}MODULE_ELEMENT;
#endif

#define LED_ON		1
#define LED_OFF		0


typedef struct
{
	Uint8 port;
	Uint8 index;
}LED_PIN_DEF;

enum
{
	LED_1 = 0,
	LED_2,
	LED_3,
	LED_4,
	LED_5,
	LED_6,
	LED_7 ,
	LED_8 ,
	LED_9 ,
	LED_10 ,
	LED_11 ,
	LED_12 ,
	LED_ALL,
};


GLOBAL LED_PIN_DEF LedTrain[];

GLOBAL void StartShowLed();
GLOBAL void LedIdle();

GLOBAL void ShowNextLedElement();

#undef GLOBAL


/******************************************************************************/
#endif
/******************************************************************************/
